name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install nasm build-essential mtools libguestfs-tools
    - name: nasm && image
      run: cd bootloader && nasm -f bin bootloader.asm -o bootloader.bin && dd if=bootloader.bin of=bootable.img bs=512 count=1
