name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: cd scripts && ./dependencies.sh
    - name: Compile && Cleanup
      run: cd scripts && ./compile.sh $$ ./cleanup.sh
